version: '3.1'

services:
  app:
    build: 
      context: .
      args:
        VARIANT: "11"
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "true"
        INSTALL_NODE: "false"
        NODE_VERSION: lts/*
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - rya_dev

  rya:
    image: ktipp/rya-docker-dev:v1.0.0
    ports:
      - 8080:8080
      - 2181:2181
    environment:
      ZOOKEEEPERS: rya
      ZOO_MY_ID: 1
    networks:
      - rya_dev

networks:
  rya_dev: